### PR TITLE
fix: typos in documentation files

### PR DESCRIPTION
**Pull request by leopardracer**
This pull request contains changes to improve clarity, correctness and structure.
Description correction:

Corrected "specifity" to "specificity".
Corrected "Metadatax" to "Metadata".

Please review the changes and let me know if any additional changes are needed.

### CODE REVIEW

**Review by Eikix — APPROVED** [review]
ty

**Comment by leopardracer** [comment]
> ty
> 
> 

what do you mean?

**Comment by Eikix** [comment]
> > ty
> 
> what do you mean?

"thank you"

you need to fix formatting btw

**Comment by leopardracer** [comment]
@Eikix Hello, I have made the corrections. Could you please check them?

**Comment by leopardracer** [comment]
@Eikix Hi, can I create a new pull request with the typo fixes that were mentioned above and also fix formatting btw?

**Pull request closed without merging**
