### PR TITLE
docker: improve docker compose

### PR DESCRIPTION
**Pull request by d-roak**
Time spent on this PR:

Resolves: #812 

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing

# What is the new behavior?

# Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by greged93** [comment]
@d-roak can I review this?

**Comment by d-roak** [comment]
humm, no. gimme a couple hours for me to resolve the conflicts and test it

**Comment by d-roak** [comment]
image

i was having this issue, but it seems that it also exists in  the main branch, when you try to run the katana docker compose. Any clue @greged93 @Eikix ?

**Comment by greged93** [comment]
hey @d-roak, can we close this?

**Comment by d-roak** [comment]
네~~

**Comment by greged93** [comment]
감사해요

**Pull request closed without merging**
