### PR TITLE
dev: fix contracts_Precompiles not found bug

### PR DESCRIPTION
**Pull request by imotai**
This pull request fixes the issue of encountering cannot stat 'build/ssj/contracts_Precompiles.contract_class.json': No such file or directory when running setup.

```
    - IUniswapV2Callee.0.8.24
    - IUniswapV2ERC20.0.8.24
    - IUniswapV2Factory.0.8.24
    - IUniswapV2Pair.0.8.24
    - PlainOpcodesTest
make[1]: Leaving directory '/mnt/ssd3/opensource/kakarot-rpc/lib/kakarot'
mv: cannot stat 'build/ssj/contracts_Precompiles.contract_class.json': No such file or directory
make: *** [Makefile:15: setup] Error 1

```
Time spent on this PR: half hour

Resolves: #905

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build-related changes
- [ ] Documentation content changes
- [ ] Testing

# What is the new behavior?

```
make[1]: Leaving directory '/mnt/ssd3/opensource/kakarot-rpc/lib/kakarot'
./scripts/extract_abi.sh
Starting build process
Removing existing build directory ./.kakarot
Creating new build directory ./.kakarot
Finding JSON files in ./lib/kakarot/build to process...
Processing file: ./lib/kakarot/build/fixtures/ERC20.json
Creating subdirectories in ./.kakarot/artifacts/fixtures and ./.kakarot/build/fixtures
Processing file: ./lib/kakarot/build/fixtures/EVM.json
Creating subdirectories in ./.kakarot/artifacts/fixtures and ./.kakarot/build/fixtures
Processing file: ./lib/kakarot/build/fixtures/replace_class.json
Creating subdirectories in ./.kakarot/artifacts/fixtures and ./.kakarot/build/fixtures
Processing file: ./lib/kakarot/build/contract_account.json
Creating subdirectories in ./.kakarot/artifacts and ./.kakarot/build
Processing file: ./lib/kakarot/build/proxy.json
Creating subdirectories in ./.kakarot/artifacts and ./.kakarot/build
Processing file: ./lib/kakarot/build/OpenzeppelinAccount.json
Creating subdirectories in ./.kakarot/artifacts and ./.kakarot/build
Processing file: ./lib/kakarot/build/precompiles.json
Creating subdirectories in ./.kakarot/artifacts and ./.kakarot/build
Processing file: ./lib/kakarot/build/externally_owned_account.json
Creating subdirectories in ./.kakarot/artifacts and ./.kakarot/build
Processing file: ./lib/kakarot/build/kakarot.json
Creating subdirectories in ./.kakarot/artifacts and ./.kakarot/build
Build process complete.

```

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by greged93** [comment]
Hey @imotai, thanks for the PR! Given how the names changed to Cairo helpers, we want to change this name everywhere from precompiles and not just in the make file

**Comment by imotai** [comment]
> Hey @imotai, thanks for the PR! Given how the names changed to Cairo helpers, we want to change this name everywhere from precompiles and not just in the make file
Hi @greged93 , thanks for the feedback , I will try it.

**Comment by Eikix** [comment]
Since this blocks anyone from doing `make setup` on main branch, I'm merging this asap and creating a follow-up issue.

**Review by Eikix — APPROVED** [review]
lgtm

**Pull request merged**
