### PR TITLE
reactivate indexer tests

### PR DESCRIPTION
**Pull request by eugypalu**
Resolves: #<Issue number>

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Testing

# What is the new behavior?

reactivate indexer tests

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by tcoratger** [comment]
Lgtm, pending @greged93. In a follow up PR, could we make a test util function that allows to generate a random starknet calldata for example with a comprehensible implementation of each element of the array? 

Currently, I see that the test passes but I am not really able to understand how the calldata was built and if it is correct or not. 

I would say for example that we need a function where we enter parameters (like the `to`, etc) and the function returns us the clean and well documented calldata so that anyone is able to generate a test calldata even first time contributors.

**Review by greged93 — APPROVED** [review]

**Comment by greged93** [comment]
let's maybe make an issue for this

**Comment by tcoratger** [comment]
> let's maybe make an issue for this

Don https://github.com/kkrt-labs/kakarot-rpc/issues/1417

**Comment by tcoratger** [comment]
@greged93 Can we merge or is there a blocker due to your current integration work?

**Comment by greged93** [comment]
sure let me quickly review and we can merge!

**Pull request merged**
