### PR TITLE
dev: integrate tokio-console

### PR DESCRIPTION
**Pull request by ooochoche**
Time spent on this PR: 14H

Resolves: #1446 

# Feature

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing

# What is the new behavior?

Enables debugging and profiling for async operations

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by greged93** [comment]
hey @ooochoche thank you for the PR, did you try to run the code locally? I'm not sure this will compile to be honest

**Comment by ooochoche** [comment]
@greged93 I'm currently on it. `make setup` is throwing a long error message 

https://github.com/user-attachments/assets/e807a3d5-978d-46a2-80d0-6a811f0cad9b

**Comment by greged93** [comment]
@ooochoche can you install [asdf](https://asdf-vm.com/)?

**Comment by greged93** [comment]
and with asdf you will need to install scarb version 0.7.0 and 2.6.5 I think

**Comment by ooochoche** [comment]
Alright, thanks. I'm on it.

**Comment by ooochoche** [comment]
@greged93, please can you help me out with your Telegram username so I can chat with you there? I have some questions and I think it will be better.

**Comment by greged93** [comment]
hey @ooochoche, I think it would be better if someone else takes over who has more experience with Rust and tokio

**Comment by ooochoche** [comment]
@greged93 Alright, that's fair enough. If there are less complicated issues, I'm open to working on them. Thank you.

**Pull request closed without merging**
