### PR TITLE
dev: add changelog and enforce in ci

### PR DESCRIPTION
**Pull request by ftupas**
Time spent on this PR: 0.01

Resolves: #409 

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing

# What is the new behavior?

Add a change log based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)

# Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by Eikix — COMMENTED** [review]
great PR! we're moving towards rigorous versioning!
what happens if a PR is just a bug-fix or a non important change?

**Comment by ftupas** [comment]
> great PR! we're moving towards rigorous versioning! what happens if a PR is just a bug-fix or a non important change?

Thanks! If it's a non important change, we can use [`skipLabels`](https://github.com/dangoslen/changelog-enforcer#skiplabels). Perhaps we can a special label for this i.e. `skip-changelog` or something similar

**Comment by Eikix** [comment]
> 

so i should create a label called skip-changelog?

**Review by Eikix — APPROVED** [review]
lgtm

**Pull request merged**
