### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Olexandr88**
Time spent on this PR:

Resolves: #<Issue number>

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing

# What is the new behavior?

# Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by greged93** [comment]
can you close this PR and add the change you made to the other please

**Comment by Olexandr88** [comment]
Yes, of course I can add changes and close, but please explain exactly what changes to add. Because I'm already a little confused.

**Comment by greged93** [comment]
You opened 2 PR's for README, combine them into one PR

**Comment by Olexandr88** [comment]
united

**Review by greged93 — APPROVED** [review]

**Pull request merged**
