### PR TITLE
add `WithOtherFields` for `TransactionReceipt`

### PR DESCRIPTION
**Pull request by tcoratger**

### CODE REVIEW

**Comment by Eikix** [comment]
Test failing

**Comment by tcoratger** [comment]
> Test failing

@Eikix It wasn't a code issue, it's our CI that's failing randomly right for a week or so now. 

We'll have to look at this closely, but in anyway it wasn't the code because the fail that occurred had nothing to do with the added parts and relaunching the tests gives green light on the CI.

**Comment by greged93** [comment]
Could we try running the whole system locally with docker compose and checking that out of Cairo steps transactions are indexed correctly ?

**Comment by greged93** [comment]
Best would be a real test but this works too

**Comment by tcoratger** [comment]
@greg Good timing, just wrote an issue to track this properly https://github.com/kkrt-labs/kakarot-rpc/issues/1457

**Comment by Eikix** [comment]
> Best would be a real test but this works too

i think writing a test for it is shorter than trying locally

**Comment by tcoratger** [comment]
@Eikix I think we can merge this to move forward and do the test in a follow up PR tomorrow as per https://github.com/kkrt-labs/kakarot-rpc/issues/1457

**Comment by tcoratger** [comment]
@Eikix Can we merge this so that @eugypalu can move on with tests?

**Review by greged93 — APPROVED** [review]

**Pull request merged**
