### PR TITLE
ci: add on release trigger for docker image

### PR DESCRIPTION
**Pull request by d-roak**
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/751)

### CODE REVIEW

**Review by Eikix — APPROVED** [review]
i hereby approve this co-authored pr

**Comment by d-roak** [comment]
가보자고

**Review by Eikix — CHANGES_REQUESTED** [review]
tests are failing...

explored bytecode because bytecode is now packed in kakarot but that's only in inner layer! bytecode() entrypoint is unchanged.

explored some bugs due to katana without much success

it's unclear.

pulled main branch and tests run fine! so it's the latest bump that breaks everything.

**Comment by d-roak** [comment]
i reverted the bump of kakarot since that's a separate issue. It should be passing the tests now

**Review by Eikix — APPROVED** [review]

**Pull request merged**
